---
repos:
  - repo: local
    hooks:
      - id: strict-python-types
        name: strict Python types
        entry: uv run --frozen --all-groups basedpyright
        language: system
        pass_filenames: false
        always_run: true
